exports = 'default'

external = [
  'sucrase/register',
  'ws',
]

[input]
  client = './lib/client.js'
  server = './lib/server.js'
  'server.browser' = './lib/server.browser.js'
  worker-process = './lib/worker-process.js'
